### ISSUE TITLE
Workflow trigger considerations

### ISSUE THREAD

**Issue by wei** [repo-sync/repo-sync#2]
Sample workflow file
```
name: "Sync wei/pull:master to pull"

on:
  schedule:
  - cron: "*/60 * * * *"
  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: wei/github-sync@master
      name: repo-sync
      env:
        SOURCE_REPO: "wei/pull"
        SOURCE_BRANCH: "master"
        DESTINATION_BRANCH: "pull"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH:$DESTINATION_BRANCH
```

As discussed, the workflow file will reside in the destination repository (for our use-case, a workflow file will exist in each repository). The workflow in the destination repository has write access through the built-in `secrets.GITHUB_TOKEN`. 

Cron is a way to allow maximum flexibility in the server/host and permission of the source repo. [Repository dispatch event](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event) would be a great way to trigger the workflow when source repository sees a push action, but the request data and format of Github's built-in [webhooks](https://developer.github.com/webhooks/) is quite different from what Repository dispatch event call takes in, therefore, a middleware/webhook proxy/or an action could to be setup to support this use-case in the future. But for now we are opting for a cron job every 15 minutes. If no updates were found, the job will succeed silently without taking action.
