### ISSUE TITLE
Storing Configuration Variables

### ISSUE THREAD

**Issue by wei** [repo-sync/repo-sync#4]
There are two ways to use sync, unidirectional and bidirectional.

## Unidirectional `owner/repoA:master → owner/repoB:master`

Configuration variables can be put directly in workflow yaml. 
ps. setup for bidirectional flow (using secrets) will also work with unidirectional flow.

<details>
 <summary>Unidirectional setup</summary>

#### `repoB/.github/workflows/sync.yml`
```yaml
name: Sync repository

on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  repo-sync:
    name: Sync repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: wei/github-sync@v1
      name: Sync repository to branch
      env:
        SOURCE_REPO: "owner/repoA"
        SOURCE_BRANCH: "master"
        DESTINATION_BRANCH: "from-repoA"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH:$DESTINATION_BRANCH
    - uses: wei/pull-request@v1
      name: Create pull request
      env:
        SOURCE_BRANCH: "from-repoA"
        DESTINATION_BRANCH: "master"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
</details>

## Bidirectional `owner/repoA:master ⇄ owner/repoB:master`

For bidirectional use-cases, because master branches are synced, the workflow yaml file will be the same between repoA and repoB. Because of this, the values of those variables need to be kept separately from the codebase. However, there is no easy way to store key value pairs that is tied to a repository except for the recently introduced `Secrets`. Therefore, that is the route I've chosen for now.

<details>
 <summary>Bidirectional setup</summary>

#### `repoA/settings/secrets`
```
SOURCE_REPO=owner/repoB
SOURCE_BRANCH=master
DESTINATION_BRANCH=from-repoB
PR_DESTINATION_BRANCH=master
```

#### `repoB/settings/secrets`
```
SOURCE_REPO=owner/repoA
INTERMEDIATE_BRANCH=from-repoA
```

#### `repoA/.github/workflows/sync.yml` AND `repoB/.github/workflows/sync.yml`
```yaml
name: Sync repository

on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  repo-sync:
    name: Sync repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: wei/github-sync@v1
      name: Sync repository to branch
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SOURCE_REPO_PRIVATE_KEY }}
        SOURCE_REPO: ${{ secrets.SOURCE_REPO }}
        SOURCE_BRANCH: "master"
        INTERMEDIATE_BRANCH: ${{ secrets.INTERMEDIATE_BRANCH }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH:$INTERMEDIATE_BRANCH
    - uses: wei/pull-request@v1
      name: Create pull request
      env:
        SOURCE_BRANCH: ${{ secrets.INTERMEDIATE_BRANCH }}
        DESTINATION_BRANCH: "master"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
</details>

Any feedback/suggestions on this flow and using secrets to store config variables?
